
get http://localhost:3000/v1/post/657eda87eeabab02a5157845

###
post http://localhost:3000/v1/auth/login

post-Content-Type: aplication/json
{
    "email":"bambang@gmail.com",
    "password":"password"
}